@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2ODM5MzI2OTB9.NujvPJ1Yyga2cB9L8dYYUVXDAzlY9m3LJkPckMs2lvY

### Session Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "mike89@test.com",
"password": "password"
}

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{"first_name": "Will",
"last_name": "Witzgerald",
"email": "Will89@test.com",
"age": 33,
"orientation": "Straight",
"preferred_orientation": "Straight",
"religion": "Christian",
"location": "Pittsburgh",
"password": "password",
"password_confirmation": "password"
}

### User Show
GET http://localhost:3000/users/4.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### User Index
GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### User Update
PATCH http://localhost:3000/users/3.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "photos": "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
}


### User Destroy
DELETE http://localhost:3000/users/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Genre Create
POST http://localhost:3000/genres.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Rock",
  "band_id": 1,
  "user_id": 2
}

### Genre Show
GET http://localhost:3000/genres/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Genre Index
GET http://localhost:3000/genres.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Genre Update
PATCH http://localhost:3000/genres/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Math Rock"
}

### Genre Delete
DELETE http://localhost:3000/genres/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Band Create
POST http://localhost:3000/bands.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Polyphia",
  "notes": "I like them",
  "genre_id": 2,
  "user_id": 2
}

### Band Show
GET http://localhost:3000/bands/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Band Index
GET http://localhost:3000/bands.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Band Update
PATCH http://localhost:3000/bands/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Polyphia"
}

### Band Delete
DELETE http://localhost:3000/bands/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Song Create
POST http://localhost:3000/songs.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "G.O.A.T.",
  "band_id": 2,
  "user_id": 2
}

### Song Show
GET http://localhost:3000/songs/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Song Index
GET http://localhost:3000/songs.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Song Update
PATCH http://localhost:3000/songs/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "G.O.A.T."
}

### Song Delete
DELETE http://localhost:3000/songs/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Lyric Create
POST http://localhost:3000/lyrics.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "lyrics": "Instrumental",
  "notes": "Greatest Song of All Time!",
  "song_id": 2,
  "user_id": 2
}

### Lyric Show
GET http://localhost:3000/lyrics/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Lyric Index
GET http://localhost:3000/lyrics.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Lyric Update
PATCH http://localhost:3000/lyrics/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "notes": "The G.O.A.T.!"
}

### Lyric Delete
DELETE http://localhost:3000/lyrics/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}


### Match Create
POST http://localhost:3000/matches.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "user_id": 4,
  "match_id": 2
}

### Match Show
GET http://localhost:3000/matches/3.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Match Index
GET http://localhost:3000/matches.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Match Update
PATCH http://localhost:3000/matches/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "notes": "The G.O.A.T.!"
}

### Match Delete
DELETE http://localhost:3000/matches/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}