@jwt = "jwt"

### Session Create
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
"email": "mike89@test.com",
"password": "password"
}

### User Create
POST http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{"first_name": "Micheal",
"last_name": "Fitzgerald",
"email": "mike89@test.com",
"age": 33,
"orientation": "Straight",
"preferred_orientation": "Straight",
"religion": "Christian",
"location": "Pittsburgh",
"password": "password",
"password_confirmation": "password"
}

### User Show
GET http://localhost:3000/users/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### User Index
GET http://localhost:3000/users.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### User Update
PATCH http://localhost:3000/users/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "first_name": "Michelle"
}


### User Destroy
DELETE http://localhost:3000/users/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Genre Create
POST http://localhost:3000/genres.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Rock",
  "band_id": 1,
  "user_id": 2
}

### Genre Show
GET http://localhost:3000/genres/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Genre Index
GET http://localhost:3000/genres.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

### Genre Update
PATCH http://localhost:3000/genres/1.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "name": "Math Rock"
}