jergen = User.create!({first_name: "Jergen", last_name: "Vongina", email: "JVong@test.com", age: 19, orientation: "straight", preferred_orientation: nil, religion: "Morman", location: "Salt Lake City", password_digest: "$2a$12$h3VY60hF/1hHyDuEOftyGetsA0oCccnZuPaiMV.A.xAmq8CfBMUIK", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684119601/fccnxehwzdjljetn8qab.jpg", gender: "Nonbinary"})
casey = User.create!({first_name: "Casey", last_name: "Bruchwalski", email: "cb99@test.com", age: 23, orientation: "straight", preferred_orientation: nil, religion: "christian", location: "pittsburgh", password_digest: "$2a$12$Y3G1C/fQr6dY4Pyzu1.5bep1Unx2UJfU5MRGjmJZ00Ef0WwEXXkLu", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684117993/q92ewuppaodsftgrrtz3.jpg", gender: "Female"})
shirona = User.create!({first_name: "Shirona", last_name: "La'Cheeks", email: "SCheeks@test.com", age: 41, orientation: "straight", preferred_orientation: nil, religion: "chrisitian", location: "Atlanta", password_digest: "$2a$12$42aRhrt8JiBV0eXO2ACNzOi0qVMWFQAoAxkQyazSVCBWjS06/yAbW", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684119749/m2cnbcxza4j0tczfzanq.jpg", gender: "Female"})
roberta = User.create!({first_name: "Roberta", last_name: "Shugalipz", email: "RLipz@test.com", age: 101, orientation: "straight", preferred_orientation: nil, religion: "Catholic", location: "Las Vegas", password_digest: "$2a$12$K9dPV3hDB24iWfBHnif6qe7BaG3PPJ4xWt5bcfRmq3V8JANe6Hk6O", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684120389/ow9e63neeibx6f3lxt4s.jpg", gender: "Female"})
rae = User.create!({first_name: "Rae", last_name: "Littiner", email: "RLit@test.com", age: 54, orientation: "Any", preferred_orientation: nil, religion: "Atheist", location: "Des Moines", password_digest: "$2a$12$gWtRMQ8Vk5Fs784XH8stVueDF2qO51BYG2LcxHFDdq/RuXyE0VEua", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684119912/zah5qnm9wxtlzip5tgxq.jpg", gender: "Trans"})
dan = User.create!({first_name: "Dan", last_name: "Billiard", email: "DanB@test.com", age: 24, orientation: "gay", preferred_orientation: nil, religion: "Catholic", location: "harrisburg", password_digest: "$2a$12$oseydByOhrCM41/NR8uA1uE/OjHMkEv1DUfma8NBviaYAA6nByBvW", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684115970/jbn9nefjucmtygau1qs1.jpg", gender: "Male"})
mike = User.create!({first_name: "Mike", last_name: "Fitzgerald", email: "micheal.c.fitzgerald@gmail.com", age: 33, orientation: "straight", preferred_orientation: nil, religion: "christian", location: "pittsburgh", password_digest: "$2a$12$nQRKVhaE.zSyhOaRJ1obauWzOjqvxUhJIRJPD0J.DVzGrcOeIBmXC", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684117868/fb7uoyjcwtvnbrgavztk.jpg", gender: "Male"})
bubble = User.create!({first_name: "Bubble", last_name: "Winthrop", email: "Bwin@test.com", age: 69, orientation: "Not Sure", preferred_orientation: nil, religion: "buddhist", location: "Philadelphia", password_digest: "$2a$12$EBScIvMENeOFqbq3SnFvY.vrE0L3WvJ2RM5QrUqtrWbScaKC0grV6", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684119434/zzwirfdmfztdwwckzjds.jpg", gender: "Male"})
tanzy = User.create!({first_name: "Tanzy", last_name: "Butternuts", email: "TanNuts@test.com", age: 27, orientation: "straight", preferred_orientation: nil, religion: "Scientology", location: "Alamo", password_digest: "$2a$12$C464yJmse/JHpBD/X6ZLgODOW9Hoc3PUxcIXReyJfkQjV1pSdlohC", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684120057/tbuoigtdisu5kozicfa5.jpg", gender: "Male"})
sylvester = User.create!({first_name: "Sylvester", last_name: "Montoya", email: "SMon@test.com", age: 87, orientation: "gay", preferred_orientation: nil, religion: "atheist", location: "San Francisco", password_digest: "$2a$12$2kPX1.uNr8MrtdI09PvEUeRt8b86/HAmXtDjuQiL3/aaPNXodgRCO", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684120507/az2xt03mzlwv6uoe60xu.webp", gender: "Male"})
katherine = User.create!({first_name: "Katherine", last_name: "Evans", email: "KEvans@test.com", age: 33, orientation: "straight", preferred_orientation: nil, religion: "Atheist", location: "Chicago", password_digest: "$2a$12$Ev3.BcZUe9CzalG39Y4pWuM1EXDuX02/.xaag7/Hx2oV4O3YiGVCi", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684197691/cxkyt0z6nmzqbbgimwwq.jpg", gender: nil})
jay = User.create!({first_name: "Jay", last_name: "Wengrow", email: "jwen@test.com", age: 35, orientation: "straight", preferred_orientation: nil, religion: "Jewish", location: "Chicago", password_digest: "$2a$12$0VTJqjr0KLFLrbCXhkxsTuSBJ597mVT51Es6AZYSXlgjSAmMugaM.", photos: "https://res.cloudinary.com/duxcjwcda/image/upload/v1684282451/qbqzdnkwqx3ev77gglxs.jpg", gender: nil})

Genre.create!([{name: "Rock", band_id: 1, user_id: 2}])
Genre.create!([{name: "country", band_id: nil, user_id: jergen.id}])
Genre.create!({name: "jazz", band_id: nil, user_id: jergen.id})
Genre.create!({name: "pop", band_id: nil, user_id: jergen.id})
Genre.create!({name: "classical", band_id: nil, user_id: jergen.id})
Genre.create!({name: "math rock", band_id: nil, user_id: jergen.id})
Genre.create!({name: "country", band_id: nil, user_id: casey.id})
Genre.create!({name: "jazz", band_id: nil, user_id: casey.id})
Genre.create!({name: "pop", band_id: nil, user_id: casey.id})
Genre.create!({name: "country", band_id: nil, user_id: shirona.id})
Genre.create!({name: "rock", band_id: nil, user_id: shirona.id})
Genre.create!({name: "pop", band_id: nil, user_id: shirona.id})
Genre.create!({name: "math rock", band_id: nil, user_id: shirona.id})
Genre.create!({name: "country", band_id: nil, user_id: roberta.id})
Genre.create!({name: "jazz", band_id: nil, user_id: roberta.id})
Genre.create!({name: "classical", band_id: nil, user_id: roberta.id})
Genre.create!({name: "rock", band_id: nil, user_id: rae.id})
Genre.create!({name: "country", band_id: nil, user_id: rae.id})
genre = Genre.create!({name: "math rock", band_id: nil, user_id: rae.id})
Genre.create!({name: "rock", band_id: nil, user_id: dan.id})
Genre.create!({name: "pop", band_id: nil, user_id: dan.id})
Genre.create!({name: "math rock", band_id: nil, user_id: dan.id})
Genre.create!({name: "jazz", band_id: nil, user_id: mike.id})
Genre.create!({name: "country", band_id: nil, user_id: bubble.id})
Genre.create!({name: "classical", band_id: nil, user_id: bubble.id})
Genre.create!({name: "rock", band_id: nil, user_id: bubble.id})
Genre.create!({name: "jazz", band_id: nil, user_id: tanzy.id})
Genre.create!({name: "pop", band_id: nil, user_id: tanzy.id})
Genre.create!({name: "rock", band_id: nil, user_id: sylvester.id})
Genre.create!({name: "pop", band_id: nil, user_id: sylvester.id})
Genre.create!({name: "classical", band_id: nil, user_id: katherine.id})
Genre.create!({name: "pop", band_id: nil, user_id: katherine.id})
Genre.create!({name: "country", band_id: nil, user_id: katherine.id})
Genre.create!({name: "jazz", band_id: nil, user_id: jay.id})
Genre.create!({name: "rock", band_id: nil, user_id: jay.id})
Genre.create!({name: "country", band_id: nil, user_id: jay.id})
Genre.create!({name: "math rock", band_id: nil, user_id: jay.id})
band = Band.create!([
  {name: "Polyphia", notes: "I like them", genre_id: genre.id, user_id: shirona.id}
])
song = Song.create!([
  {name: "G.O.A.T.", band_id: band.id, user_id: jay.id}
])
